import { Type } from '@sinclair/typebox';
import type { Static } from '@sinclair/typebox';

// Generated by RealMap embedding pipeline — do not edit manually
export const CookingMethodsSchema = Type.Object({
  "baking": Type.Optional(Type.Number()),
  "boiling": Type.Optional(Type.Number()),
  "braising": Type.Optional(Type.Number()),
  "brewing": Type.Optional(Type.Number()),
  "confit": Type.Optional(Type.Number()),
  "curing": Type.Optional(Type.Number()),
  "deep_frying": Type.Optional(Type.Number()),
  "drying": Type.Optional(Type.Number()),
  "earth_oven": Type.Optional(Type.Number()),
  "fermenting": Type.Optional(Type.Number()),
  "foraging": Type.Optional(Type.Number()),
  "frying": Type.Optional(Type.Number()),
  "grilling": Type.Optional(Type.Number()),
  "marinating": Type.Optional(Type.Number()),
  "pickling": Type.Optional(Type.Number()),
  "poaching": Type.Optional(Type.Number()),
  "pounding": Type.Optional(Type.Number()),
  "preserving": Type.Optional(Type.Number()),
  "raw": Type.Optional(Type.Number()),
  "roasting": Type.Optional(Type.Number()),
  "smoking": Type.Optional(Type.Number()),
  "steaming": Type.Optional(Type.Number()),
  "stewing": Type.Optional(Type.Number()),
  "stir_frying": Type.Optional(Type.Number()),
});

export type CookingMethods = Static<typeof CookingMethodsSchema>;
